Repository arsalan0c/cdp-hs, pull requests merged in 2022-10, with the labels that each got.

#31 Fix doc bugs
  cdp/src/CDP/Domains/Accessibility.hs
  cdp/src/CDP/Domains/Animation.hs
  cdp/src/CDP/Domains/Audits.hs
  cdp/src/CDP/Domains/BackgroundService.hs
  cdp/src/CDP/Domains/BrowserTarget.hs
  cdp/src/CDP/Domains/CSS.hs
  cdp/src/CDP/Domains/CacheStorage.hs
  cdp/src/CDP/Domains/Cast.hs
  cdp/src/CDP/Domains/DOMDebugger.hs
  cdp/src/CDP/Domains/DOMPageNetworkEmulationSecurity.hs
  cdp/src/CDP/Domains/DOMSnapshot.hs
  cdp/src/CDP/Domains/DOMStorage.hs
  cdp/src/CDP/Domains/Database.hs
  cdp/src/CDP/Domains/Debugger.hs
  cdp/src/CDP/Domains/DeviceOrientation.hs
  cdp/src/CDP/Domains/EventBreakpoints.hs
  cdp/src/CDP/Domains/Fetch.hs
  cdp/src/CDP/Domains/HeadlessExperimental.hs
  cdp/src/CDP/Domains/HeapProfiler.hs
  cdp/src/CDP/Domains/IO.hs
  cdp/src/CDP/Domains/IndexedDB.hs
  cdp/src/CDP/Domains/Input.hs
  cdp/src/CDP/Domains/Inspector.hs
  cdp/src/CDP/Domains/LayerTree.hs
  cdp/src/CDP/Domains/Log.hs
  cdp/src/CDP/Domains/Media.hs
  cdp/src/CDP/Domains/Memory.hs
  cdp/src/CDP/Domains/Overlay.hs
  cdp/src/CDP/Domains/Performance.hs
  cdp/src/CDP/Domains/PerformanceTimeline.hs
  cdp/src/CDP/Domains/Profiler.hs
  cdp/src/CDP/Domains/Runtime.hs
  cdp/src/CDP/Domains/ServiceWorker.hs
  cdp/src/CDP/Domains/Storage.hs
  cdp/src/CDP/Domains/SystemInfo.hs
  cdp/src/CDP/Domains/Tethering.hs
  cdp/src/CDP/Domains/Tracing.hs
  cdp/src/CDP/Domains/WebAudio.hs
  cdp/src/CDP/Domains/WebAuthn.hs
  src/CDP/Gen/Program.hs
Labels: documentation

#46 subscribe + mfix example
  examples/subscribe.hs
Labels: documentation

#47 Update commands
  default.nix
  examples/open-twitter.hs
  examples/print-page.hs
  examples/subscribe.hs
  gen/CDP/Gen/Program.hs
  gen/CDP/Gen/Snippets.hs
  src/CDP.hs
  src/CDP/Domains.hs
  src/CDP/Domains/Accessibility.hs
  src/CDP/Domains/Animation.hs
  src/CDP/Domains/Audits.hs
  src/CDP/Domains/BackgroundService.hs
  src/CDP/Domains/BrowserTarget.hs
  src/CDP/Domains/CSS.hs
  src/CDP/Domains/CacheStorage.hs
  src/CDP/Domains/Cast.hs
  src/CDP/Domains/DOMDebugger.hs
  src/CDP/Domains/DOMPageNetworkEmulationSecurity.hs
  src/CDP/Domains/DOMSnapshot.hs
  src/CDP/Domains/DOMStorage.hs
  src/CDP/Domains/Database.hs
  src/CDP/Domains/Debugger.hs
  src/CDP/Domains/DeviceOrientation.hs
  src/CDP/Domains/EventBreakpoints.hs
  src/CDP/Domains/Fetch.hs
  src/CDP/Domains/HeadlessExperimental.hs
  src/CDP/Domains/HeapProfiler.hs
  src/CDP/Domains/IO.hs
  src/CDP/Domains/IndexedDB.hs
  src/CDP/Domains/Input.hs
  src/CDP/Domains/Inspector.hs
  src/CDP/Domains/LayerTree.hs
  src/CDP/Domains/Log.hs
  src/CDP/Domains/Media.hs
  src/CDP/Domains/Memory.hs
  src/CDP/Domains/Overlay.hs
  src/CDP/Domains/Performance.hs
  src/CDP/Domains/PerformanceTimeline.hs
  src/CDP/Domains/Profiler.hs
  src/CDP/Domains/Runtime.hs
  src/CDP/Domains/ServiceWorker.hs
  src/CDP/Domains/Storage.hs
  src/CDP/Domains/SystemInfo.hs
  src/CDP/Domains/Tethering.hs
  src/CDP/Domains/Tracing.hs
  src/CDP/Domains/WebAudio.hs
  src/CDP/Domains/WebAuthn.hs
  src/CDP/Internal/Utils.hs
  src/CDP/Runtime.hs
  test/Commands/Main.hs
  test/Events/Main.hs
Labels: codequality, interface

#51 Fix build
  gen/CDP/Gen/Program.hs
Labels: bug

#50 Use hspec for tests
  gen/CDP/Gen/Program.hs
  package.yaml
  src/CDP.hs
  test/Commands/Main.hs
  test/Events/Main.hs
  test/Main.hs
Labels: test

#53 Add existential type and eliminator for Command
  src/CDP.hs
  src/CDP/Runtime.hs
  test/Main.hs
Labels: enhancement, interface

#54 Add endpoints
  examples/endpoints.hs
  package.yaml
  src/CDP.hs
  src/CDP/Endpoints.hs
  src/CDP/Internal/Endpoints.hs
  src/CDP/Internal/Utils.hs
  src/CDP/Runtime.hs
  test/Main.hs
Labels: enhancement

#60 Map CDP string to Haskell Text instead of String
  examples/open-twitter.hs
  examples/print-page.hs
  examples/sessions.hs
  examples/subscribe.hs
  gen/CDP/Gen/Program.hs
  src/CDP.hs
  src/CDP/Domains/Accessibility.hs
  src/CDP/Domains/Animation.hs
  src/CDP/Domains/Audits.hs
  src/CDP/Domains/BackgroundService.hs
  src/CDP/Domains/BrowserTarget.hs
  src/CDP/Domains/CSS.hs
  src/CDP/Domains/CacheStorage.hs
  src/CDP/Domains/Cast.hs
  src/CDP/Domains/DOMDebugger.hs
  src/CDP/Domains/DOMPageNetworkEmulationSecurity.hs
  src/CDP/Domains/DOMSnapshot.hs
  src/CDP/Domains/DOMStorage.hs
  src/CDP/Domains/Database.hs
  src/CDP/Domains/Debugger.hs
  src/CDP/Domains/EventBreakpoints.hs
  src/CDP/Domains/Fetch.hs
  src/CDP/Domains/HeadlessExperimental.hs
  src/CDP/Domains/HeapProfiler.hs
  src/CDP/Domains/IO.hs
  src/CDP/Domains/IndexedDB.hs
  src/CDP/Domains/Input.hs
  src/CDP/Domains/Inspector.hs
  src/CDP/Domains/LayerTree.hs
  src/CDP/Domains/Log.hs
  src/CDP/Domains/Media.hs
  src/CDP/Domains/Memory.hs
  src/CDP/Domains/Overlay.hs
  src/CDP/Domains/Performance.hs
  src/CDP/Domains/PerformanceTimeline.hs
  src/CDP/Domains/Profiler.hs
  src/CDP/Domains/Runtime.hs
  src/CDP/Domains/ServiceWorker.hs
  src/CDP/Domains/Storage.hs
  src/CDP/Domains/SystemInfo.hs
  src/CDP/Domains/Tethering.hs
  src/CDP/Domains/Tracing.hs
  src/CDP/Domains/WebAudio.hs
  src/CDP/Domains/WebAuthn.hs
  src/CDP/Internal/Utils.hs
  src/CDP/Runtime.hs
  test/Main.hs
Labels: codequality, interface

#61 Map any CDP type to Aeson.Value
  .github/workflows/build.yaml
  .github/workflows/chrome.json
  gen/CDP/Gen/Program.hs
  src/CDP/Domains/Accessibility.hs
  src/CDP/Domains/DOMPageNetworkEmulationSecurity.hs
  src/CDP/Domains/Database.hs
  src/CDP/Domains/Runtime.hs
Labels: bug, typing, interface
